baseURL = 'http://localhost:1313/'
languageCode = 'zh-cn'
title = 'Matthew的博客'
theme = 'PaperMod'

[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  disableSpecial1stPost = true
[params.assets]
  customCSS = ["css/extra.css"]

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true



[params.homeInfoParams]
  Title = "Hi，我是某某"
  Content = "一句话自我介绍 + 关注方向。"

[params.profileMode]
  enabled = true
  title = "Matthew"
  subtitle = "土木->金融->量化->数据库产品经理"
  imageUrl = "/img/avatar.jpg"   # 放到 static/img/avatar.png
  imageWidth = 120
  imageHeight = 120
[[params.profileMode.buttons]]
  name = "关于我"
  url = "/about/"
[[params.profileMode.buttons]]
  name = "全部文章"
  url = "/posts/"
